/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realestateapp;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import realestateapp.models.User;
import realestateapp.models.Property;

// Κλάση AddUserPropertyForm - Διαχειρίζεται την προσθήκη νέου χρήστη και ακινήτου
public class AddUserPropertyForm extends javax.swing.JFrame {

    /**
     * Creates new form AddUserPropertyForm
     */
    // Ιδιωτικά πεδία για την αποθήκευση της επιλεγμένης εικόνας και της κατάστασης αποθήκευσης
    private File selectedImage;
    private boolean isSaved = false;
    private String adminUsername;
    private String selectedImagePath;
    // Constructor της φόρμας, λαμβάνει το όνομα χρήστη του admin
    public AddUserPropertyForm(String adminUsername) {
        this.adminUsername = adminUsername;
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblFinalPrice = new javax.swing.JLabel();
        txtFinalPrice = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        btnSelectImage = new javax.swing.JButton();
        lblImagePreview = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnBackToMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Προσθήκη Χρήστη & Ακινήτου");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Όνομα:");

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });

        lblLastName.setText("Επώνυμο:");

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });

        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username:");

        txtUsername.setEditable(false);

        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrice.setText("Αρχική Τιμή(€):");

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        lblFinalPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFinalPrice.setText("Τελική Τιμή με ΦΠΑ (€):");

        txtFinalPrice.setEditable(false);

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Φωτογραφία Ακινήτου:");

        btnSelectImage.setText("Επιλογή Εικόνας");
        btnSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImageActionPerformed(evt);
            }
        });

        btnSave.setText("Αποθήκευση");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Ακύρωση");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnBackToMenu.setText("Επιστροφή στο Μενού");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(82, 82, 82))
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                                .addComponent(lblImage)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                                .addComponent(btnSelectImage)
                                .addGap(57, 57, 57))))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addComponent(lblFinalPrice)
                                .addGap(18, 18, 18)
                                .addComponent(txtFinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addComponent(lblPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addComponent(lblImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(57, Short.MAX_VALUE))))
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnBackToMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFirstName)
                        .addComponent(lblImage)))
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnSelectImage)
                        .addGap(18, 18, 18)
                        .addComponent(lblImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addGap(18, 18, 18)
                .addComponent(btnBackToMenu)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Μέδοδος για την δημιουργία username
    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        
        if(!firstName.isEmpty() && !lastName.isEmpty())
        {
            String username = firstName.charAt(0) + lastName;
            txtUsername.setText(username.toLowerCase());
        }
    }//GEN-LAST:event_txtLastNameKeyReleased
    // Μέθοδος για τον υπολογισμό του τελικού ποσού με ΦΠΑ
    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        try
        {
            double price = Double.parseDouble(txtPrice.getText().trim().replace(",", "."));
            double finalPrice = price * 1.24;
            txtFinalPrice.setText(String.format(java.util.Locale.US,"%.2f", finalPrice));
        }
        catch(NumberFormatException e)
        {
            txtFinalPrice.setText("");// Αν δεν είναι αριθμός, καθαρίζει το πεδίο
        }
    }//GEN-LAST:event_txtPriceKeyReleased
    // Επιλογή εικόνας ακινήτου από τον υπολογιστή
    private void btnSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectImageActionPerformed
       JFileChooser fileChooser = new JFileChooser();
       fileChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));
       
       int returnValue = fileChooser.showOpenDialog(this);
       if(returnValue == JFileChooser.APPROVE_OPTION)
       {
           selectedImage = fileChooser.getSelectedFile();
           ImageIcon imageIcon = new ImageIcon(selectedImage.getAbsolutePath());
           lblImagePreview.setIcon(new ImageIcon(imageIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
       }
    }//GEN-LAST:event_btnSelectImageActionPerformed
    // Αποθήκευση των στοιχείων του χρήστη και του ακινήτου
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        String username = txtUsername.getText().trim();
        String priceText = txtPrice.getText().trim().replace(",", ".");
        String finalPriceText = txtFinalPrice.getText().trim().replace(",", ".");
        // Έλεγχος αν έχει επιλεγεί εικόνα, διαφορετικά προεπιλεγμένη εικόνα
        if (selectedImage != null) 
        {
            selectedImagePath = selectedImage.getAbsolutePath();
        }
        else
        {
            selectedImagePath = "default.png";
        }
        String imagePath = selectedImage.getAbsolutePath();
        
        if (priceText.isEmpty() || finalPriceText.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Συμπληρώστε όλα τα πεδία πριν αποθηκεύσετε!", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double initialPrice;
        double finalPrice;
        
        try
        {
            initialPrice = Double.parseDouble(txtPrice.getText());
            finalPrice = Double.parseDouble(txtFinalPrice.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Η τιμή πρέπει να είναι αριθμός!", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(firstName.isEmpty() || lastName.isEmpty() || username.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Συμπληρώστε όλα τα πεδία!", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ImageIcon imageIcon = null;
        if (imagePath != null && !imagePath.isEmpty()) 
        {
            imageIcon = new ImageIcon(new ImageIcon(imagePath).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        } 
        else 
        {         
            imageIcon = new ImageIcon("default.png"); // Προεπιλεγμένη εικόνα αν δεν έχει επιλεγεί
        }
        // Δημιουργία αντικειμένων χρήστη και ακινήτου
        User newUser = new User(firstName, lastName, username, initialPrice, finalPrice, imagePath, imageIcon, false);
        Property newProperty = new Property(initialPrice, finalPrice, selectedImagePath,"",username);
        String selectedImagePath;
        if (selectedImage != null) 
        {
            selectedImagePath = selectedImage.getAbsolutePath();
        } 
        else 
        {
            selectedImagePath = "default.png";
        }
        if (adminUsername != null) 
        {
            newProperty = new Property(initialPrice, finalPrice, selectedImagePath,"",username);
        } 
        else 
        {
        newProperty = new Property(initialPrice, finalPrice, selectedImagePath,"",username);
        }      
        // Προσθήκη του χρήστη και του ακινήτου στη βάση δεδομένων
        Database.users.add(newUser);
        Database.properties.add(newProperty);
        
        newUser.getAssignedProperties().add(newProperty);
        isSaved = true;
        JOptionPane.showMessageDialog(this, "Ο χρήστης και το ακίνητο προστέθηκαν επιτυχώς!", "Επιτυχία", JOptionPane.INFORMATION_MESSAGE);
        // Εκκαθάριση των πεδίων μετά την αποθήκευση
        txtFirstName.setText("");
        txtLastName.setText("");
        txtUsername.setText("");
        txtPrice.setText("");
        txtFinalPrice.setText("");
        lblImagePreview.setIcon(null);
    }//GEN-LAST:event_btnSaveActionPerformed
    // Επιστροφή στο κύριο μενού με έλεγχο για μη αποθηκευμένα δεδομένα
    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        if (isSaved) 
        {
            this.dispose();
            return; // Αν τα δεδομένα έχουν αποθηκευτεί, κλείνει τη φόρμα
        }
        if(!txtFirstName.getText().trim().isEmpty() || 
           !txtLastName.getText().trim().isEmpty() ||
           !txtUsername.getText().trim().isEmpty() ||
           selectedImage != null){
            int confirm = JOptionPane.showConfirmDialog(this, 
            "Έχετε εισάγει δεδομένα που δεν έχουν αποθηκευτεί. Θέλετε να αποθηκεύσετε πριν επιστρέψετε;", 
            "Μη αποθηκευμένα δεδομένα", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) 
            {
            btnSaveActionPerformed(evt); // Αποθήκευση δεδομένων αν επιλέξει "Ναι"
            } 
            else if (confirm == JOptionPane.CANCEL_OPTION) 
            {
            return; // Αν ο χρήστης πατήσει Cancel, δεν κάνει τίποτα
            }
        }
        this.dispose();// Κλείσιμο της φόρμας
    }//GEN-LAST:event_btnBackToMenuActionPerformed
    // Επιτρέπει μόνο αλφαβητικούς χαρακτήρες στο πεδίο "Όνομα"
    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ') 
        {
            evt.consume(); 
            JOptionPane.showMessageDialog(this, "Το όνομα πρέπει να περιέχει μόνο γράμματα!", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtFirstNameKeyTyped
    // Επιτρέπει μόνο αλφαβητικούς χαρακτήρες στο πεδίο "Επώνυμο"
    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ') 
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Το επώνυμο πρέπει να περιέχει μόνο γράμματα!", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtLastNameKeyTyped
    // Επιτρέπει μόνο αριθμούς και ένα δεκαδικό σημείο στο πεδίο "Αρχική Τιμή"
    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        char c = evt.getKeyChar();
    
        if (!Character.isDigit(c) && c != '.') 
        {
            evt.consume(); 
            JOptionPane.showMessageDialog(this, "Η τιμή πρέπει να είναι αριθμός!", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (c == '.' && txtPrice.getText().contains(".")) 
        {
            evt.consume(); 
        }
    }//GEN-LAST:event_txtPriceKeyTyped
    // Κουμπί "Ακύρωση" - Κλείνει τη φόρμα χωρίς να αποθηκεύσει
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    // Μέθοδος main - Εκκίνηση της φόρμας
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserPropertyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserPropertyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserPropertyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserPropertyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUserPropertyForm("admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSelectImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFinalPrice;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImagePreview;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField txtFinalPrice;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
