/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realestateapp;


import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import realestateapp.models.User;




/**
 *
 * @author ouran
 */
// Κλάση AdminPanel - Διαχειρίζεται το περιβάλλον εργασίας του διαχειριστή
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    // Μεταβλητή που αποθηκεύει το όνομα του διαχειριστή
    private String adminUsername;
    // Μεταβλητή που ελέγχει αν ο χρήστης είναι διαχειριστής
    private boolean isAdmin;
    // Constructor της κλάσης που λαμβάνει το όνομα του διαχειριστή ως όρισμα
    public AdminPanel(String adminUsername) {
        this.adminUsername = adminUsername;
        initComponents();
        loadUsersPropertiesData();
        setLocationRelativeTo(null);
        scrollPaneUsersProperties.setVisible(false);
        tblUsersProperties.setVisible(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneUsersProperties = new javax.swing.JScrollPane();
        tblUsersProperties = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menuOptions = new javax.swing.JMenu();
        menuItemAddUserProperty = new javax.swing.JMenuItem();
        menuItemViewData = new javax.swing.JMenuItem();
        menuItemEditDelete = new javax.swing.JMenuItem();
        menuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPaneUsersProperties.setAutoscrolls(true);

        tblUsersProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Αρχική Τιμή (€):", "Τελική Τιμή με ΦΠΑ (€):", "Eικόνα Ακινήτου"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneUsersProperties.setViewportView(tblUsersProperties);

        menuOptions.setBackground(new java.awt.Color(204, 204, 204));
        menuOptions.setText("Menu");

        menuItemAddUserProperty.setText("Προσθήκη Χρήστη & Ακινήτου");
        menuItemAddUserProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddUserPropertyActionPerformed(evt);
            }
        });
        menuOptions.add(menuItemAddUserProperty);

        menuItemViewData.setText("Προβολή Λίστας Χρηστών & Ακινήτων");
        menuItemViewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemViewDataActionPerformed(evt);
            }
        });
        menuOptions.add(menuItemViewData);

        menuItemEditDelete.setText("Τροποποίηση/Διαγραφή");
        menuItemEditDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditDeleteActionPerformed(evt);
            }
        });
        menuOptions.add(menuItemEditDelete);

        menuItemLogout.setText("Αποσύνδεση");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        menuOptions.add(menuItemLogout);

        menuBar.add(menuOptions);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneUsersProperties, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneUsersProperties, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Μέθοδος που εμφανίζει τη φόρμα προσθήκης χρήστη και ακινήτου
    private void menuItemAddUserPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddUserPropertyActionPerformed
        new AddUserPropertyForm(adminUsername).setVisible(true);
    }//GEN-LAST:event_menuItemAddUserPropertyActionPerformed
    // Μέθοδος που εμφανίζει τη λίστα χρηστών και ακινήτων
    private void menuItemViewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemViewDataActionPerformed
        loadUsersPropertiesData(); // Φόρτωση δεδομένων
        
        tblUsersProperties.setVisible(true); // Εμφάνιση πίνακα
        scrollPaneUsersProperties.setVisible(true); // Εμφάνιση πλαισίου κύλισης
        
        this.revalidate();// Επαναφόρτωση της διεπαφής χρήστη
        this.repaint();// Ανασχεδίαση της διεπαφής
    }//GEN-LAST:event_menuItemViewDataActionPerformed
    // Μέθοδος που ανοίγει τη φόρμα επεξεργασίας και διαγραφής χρηστών/ακινήτων
    private void menuItemEditDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditDeleteActionPerformed
        boolean isAdmin = adminUsername.equals("admin");
        new EditDeleteForm(adminUsername, isAdmin).setVisible(true);
    }//GEN-LAST:event_menuItemEditDeleteActionPerformed
    // Μέθοδος αποσύνδεσης του χρήστη και επιστροφής στην αρχική οθόνη σύνδεσης
    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        this.dispose();// Κλείσιμο του παραθύρου
        new LoginForm().setVisible(true);// Άνοιγμα της φόρμας σύνδεσης
    }//GEN-LAST:event_menuItemLogoutActionPerformed
    private void loadUsersPropertiesData() {
        // Μέθοδος φόρτωσης δεδομένων χρηστών και ακινήτων στον πίνακα
        DefaultTableModel model = (DefaultTableModel) tblUsersProperties.getModel();
        model.setRowCount(0); 
        // Έλεγχος αν η λίστα των χρηστών είναι άδεια
        if (Database.users == null) 
        {
            System.out.println("Error: Database.users is null!");
            return;
        }
        // Βρόχος που προσθέτει τους χρήστες και τις ιδιότητες τους στον πίνακα
        for (User user : Database.users) 
        {
            ImageIcon icon;
            if (user.getImagePath() != null && !user.getImagePath().isEmpty()) 
            {
                icon = new ImageIcon(new ImageIcon(user.getImagePath()).getImage().getScaledInstance(80, 60, java.awt.Image.SCALE_SMOOTH));
            } 
            else 
            {
                icon = new ImageIcon("default.png"); // Χρήση προεπιλεγμένης εικόνας αν δεν υπάρχει διαθέσιμη εικόνα
            }
            // Προσθήκη γραμμής στον πίνακα με τα στοιχεία του χρήστη
            model.addRow(new Object[]{
            user.getUsername(),
            user.getInitialPrice(),
            user.getFinalPrice(),
            user.getImagePath()
        });
        }
        tblUsersProperties.setRowHeight(60);// Ορισμός ύψους γραμμών του πίνακα
        tblUsersProperties.getColumnModel().getColumn(3).setCellRenderer(new ImageRenderer());
        
        tblUsersProperties.revalidate();// Επαναφόρτωση δεδομένων του πίνακα
        tblUsersProperties.repaint();// Ανασχεδίαση του πίνακα
        scrollPaneUsersProperties.revalidate();// Επαναφόρτωση του πλαισίου κύλισης
        scrollPaneUsersProperties.repaint();// Ανασχεδίαση του πλαισίου κύλισης
    }

    /**
     * @param args the command line arguments
     */
    // Μέθοδος εκκίνησης της εφαρμογής και εμφάνισης του AdminPanel
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel("admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAddUserProperty;
    private javax.swing.JMenuItem menuItemEditDelete;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenuItem menuItemViewData;
    private javax.swing.JMenu menuOptions;
    private javax.swing.JScrollPane scrollPaneUsersProperties;
    private javax.swing.JTable tblUsersProperties;
    // End of variables declaration//GEN-END:variables
}
