
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realestateapp;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import realestateapp.models.Property;

/**
 *
 * @author ouran
 */
public class EditPropertyDialog extends javax.swing.JDialog {
    private String selectedImagePath;
    private Property property;
    /**
     * Creates new form EditPropertyDialog
     */
    public EditPropertyDialog(java.awt.Frame parent, Property property) {
        super(parent, true);
        this.property = property;
        initComponents();
        setLocationRelativeTo(null);
        
        txtDescription.setText(property.getDescription());
        txtInitialPrice.setText(String.valueOf(property.getInitialPrice()));
        selectedImagePath = property.getImagePath();
        
        if (selectedImagePath != null && !selectedImagePath.isEmpty()) 
        {
            lblImagePreview.setIcon(new ImageIcon(new ImageIcon(selectedImagePath).getImage().getScaledInstance(100, 80, Image.SCALE_SMOOTH)));
        }
    }     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblInitialPrice = new javax.swing.JLabel();
        txtInitialPrice = new javax.swing.JTextField();
        btnChooseImage = new javax.swing.JButton();
        lblImagePreview = new javax.swing.JLabel();
        lblPlain = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        lblDescription.setText("Περιγραφή:");
        getContentPane().add(lblDescription);
        getContentPane().add(txtDescription);

        lblInitialPrice.setText("Αρχική Τιμή (€):");
        getContentPane().add(lblInitialPrice);
        getContentPane().add(txtInitialPrice);

        btnChooseImage.setText("Επιλογή Εικόνας");
        btnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnChooseImage);
        getContentPane().add(lblImagePreview);
        getContentPane().add(lblPlain);

        btnSave.setText("Αποθήκευση");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseImageActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = fileChooser.getSelectedFile();
            selectedImagePath = selectedFile.getAbsolutePath();
            
            lblImagePreview.setIcon(new ImageIcon(new ImageIcon(selectedImagePath).getImage().getScaledInstance(100, 80, Image.SCALE_SMOOTH)));
        }
    }//GEN-LAST:event_btnChooseImageActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try
        {
            String newDescription = txtDescription.getText().trim();
            double newInitialPrice = Double.parseDouble(txtInitialPrice.getText().trim());
            double newFinalPrice = newInitialPrice * 1.24;
            
            property.setInitialPrice(newInitialPrice);
            property.setFinalPrice(newFinalPrice);
            property.setDescription(newDescription);
            property.setImagePath(selectedImagePath);
            
            dispose();
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Λάθος τιμή! Παρακαλώ εισάγετε έναν αριθμό.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPropertyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPropertyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPropertyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPropertyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPropertyDialog(null, new Property(0, 0, "default.png", "", "")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblImagePreview;
    private javax.swing.JLabel lblInitialPrice;
    private javax.swing.JLabel lblPlain;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtInitialPrice;
    // End of variables declaration//GEN-END:variables
}
