/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realestateapp;

import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import realestateapp.models.User;
import javax.swing.ImageIcon;
import javax.swing.JFrame;



/**
 *
 * @author ouran
 */
// Κλάση EditDeleteForm - Παράθυρο για την τροποποίηση και διαγραφή χρηστών & ακινήτων
public class EditDeleteForm extends javax.swing.JFrame {
    // Μεταβλητές πεδία της κλάσης
    private String adminUsername;// Το όνομα χρήστη του διαχειριστή
    private boolean isAdmin; // Boolean μεταβλητή που δείχνει αν ο χρήστης είναι admin
    // Constructor της κλάσης EditDeleteForm
    public EditDeleteForm(String username, boolean isAdmin) {
        this.adminUsername = username;
        this.isAdmin = isAdmin;
        setLocationRelativeTo(null);// Τοποθετεί το παράθυρο στο κέντρο της οθόνης
        initComponents();// Αρχικοποίηση των στοιχείων της διεπαφής χρήστη
        loadUsersPropertiesData(); // Φόρτωση των δεδομένων χρηστών και ακινήτων
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);// Κλείσιμο μόνο του παραθύρου και όχι της εφαρμογής
        btnEditUserProperty.setEnabled(false);// Αρχικά απενεργοποιημένο κουμπί επεξεργασίας
        btnDeleteUserProperty.setEnabled(false);// Αρχικά απενεργοποιημένο κουμπί διαγραφής
        // Προσθήκη ListSelectionListener ώστε να ενεργοποιούνται τα κουμπιά μόνο αν επιλεγεί μια γραμμή
        tblEditUsersProperties.getSelectionModel().addListSelectionListener(event -> {
        if (!event.getValueIsAdjusting()) 
        { 
            boolean isRowSelected = tblEditUsersProperties.getSelectedRow() != -1;
            btnEditUserProperty.setEnabled(isRowSelected);
            btnDeleteUserProperty.setEnabled(isRowSelected);
        }
    });
    }
    // Μέθοδος επιστροφής του πίνακα με τις εγγραφές
    public javax.swing.JTable getTblEditUsersProperties() {
        return tblEditUsersProperties;
    }
    // Μέθοδος φόρτωσης των δεδομένων χρηστών και ακινήτων στον πίνακα
    public void loadUsersPropertiesData() {
        DefaultTableModel model = (DefaultTableModel) tblEditUsersProperties.getModel();
        model.setRowCount(0); // Διαγραφή των υπαρχόντων δεδομένων
        // Προσθήκη χρηστών και ακινήτων στον πίνακα αν είναι admin ή αν είναι ο τρέχων χρήστης
        for (User user : Database.users) 
        {
        // Αν είναι admin ή αν το username ταιριάζει με τον logged user, εμφανίζει τα δεδομένα
            if (isAdmin || user.getUsername().equals(adminUsername)) 
            {
                ImageIcon icon = null;
                if (user.getImagePath() != null && !user.getImagePath().isEmpty()) 
                {
                    icon = new ImageIcon(new ImageIcon(user.getImagePath()).getImage().getScaledInstance(80, 60, Image.SCALE_SMOOTH));
                } 
                else 
                {
                    icon = new ImageIcon("default.png"); // Default εικόνα αν δεν υπάρχει
                }
                model.addRow(new Object[]{
                    user.getUsername(),
                    user.getInitialPrice(),
                    user.getFinalPrice(),
                    icon
                });
            }
        }
        if (tblEditUsersProperties.getColumnCount() > 3) 
        {
        tblEditUsersProperties.getColumnModel().getColumn(3).setCellRenderer(new ImageRenderer());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollPaneEditUsersProperties = new javax.swing.JScrollPane();
        tblEditUsersProperties = new javax.swing.JTable();
        btnEditUserProperty = new javax.swing.JButton();
        btnDeleteUserProperty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Τροποποίηση / Διαγραφή Χρηστών & Ακινήτων");

        scrollPaneEditUsersProperties.setViewportView(tblEditUsersProperties);

        tblEditUsersProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Αρχική Τιμή (€)", "Τελική Τιμή με ΦΠΑ (€)", "Εικόνα Ακινήτου"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEditUsersProperties.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblEditUsersProperties.setGridColor(new java.awt.Color(204, 204, 204));
        tblEditUsersProperties.setRowHeight(50);
        tblEditUsersProperties.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEditUsersProperties.setShowHorizontalLines(true);
        tblEditUsersProperties.setShowVerticalLines(true);
        tblEditUsersProperties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditUsersPropertiesMouseClicked(evt);
            }
        });
        scrollPaneEditUsersProperties.setViewportView(tblEditUsersProperties);

        btnEditUserProperty.setBackground(new java.awt.Color(255, 153, 255));
        btnEditUserProperty.setText("Επεξεργασία");
        btnEditUserProperty.setEnabled(false);
        btnEditUserProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserPropertyActionPerformed(evt);
            }
        });

        btnDeleteUserProperty.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteUserProperty.setText("Διαγραφή");
        btnDeleteUserProperty.setEnabled(false);
        btnDeleteUserProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserPropertyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneEditUsersProperties, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnDeleteUserProperty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditUserProperty)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneEditUsersProperties, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditUserProperty)
                    .addComponent(btnDeleteUserProperty))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Μέθοδος διαχείρισης του κουμπιού "Επεξεργασία"
    private void btnEditUserPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserPropertyActionPerformed
        if (tblEditUsersProperties == null) 
        {
            System.out.println("tblEditUsersProperties is null!");
            return; 
        }
        int selectedRow = tblEditUsersProperties.getSelectedRow();
        if (selectedRow == -1) 
        {
            JOptionPane.showMessageDialog(this, "Παρακαλώ επιλέξτε έναν χρήστη για επεξεργασία.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {
            // Ανάκτηση δεδομένων από την επιλεγμένη γραμμή
            String username = (String) tblEditUsersProperties.getValueAt(selectedRow, 0);
            double initialPrice = (double) tblEditUsersProperties.getValueAt(selectedRow, 1);
            double finalPrice = (double) tblEditUsersProperties.getValueAt(selectedRow, 2);
            ImageIcon icon = null;
            Object cellValue = tblEditUsersProperties.getValueAt(selectedRow, 3);
            if (cellValue instanceof ImageIcon) 
            {
                icon = (ImageIcon) cellValue;
            }
            String imagePath="default.png";
            for (User user : Database.users)
            {
                if(user.getUsername().equals(username))
                {
                    imagePath = (user.getImagePath() != null && !user.getImagePath().isEmpty()) ? user.getImagePath() : "default.png";
                }
            }
            // Άνοιγμα της φόρμας επεξεργασίας
            EditUserPropertyForm editForm = new EditUserPropertyForm(this, username, initialPrice, finalPrice,imagePath);
            editForm.setVisible(true);  
        }
    }//GEN-LAST:event_btnEditUserPropertyActionPerformed
    // Μέθοδος διαχείρισης του κουμπιού "Διαγραφή"
    private void btnDeleteUserPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserPropertyActionPerformed
        int selectedRow = tblEditUsersProperties.getSelectedRow();
        if(selectedRow == -1)
        {
            JOptionPane.showMessageDialog(this, "Επιλέξτε μια εγγραφή!", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Είστε σίγουρος για τη διαγραφή;", "Επιβεβαίωση", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION)
        {
            String username = (String) tblEditUsersProperties.getValueAt(selectedRow, 0);
            Database.users.removeIf(user -> user.getUsername().equals(username));// Διαγραφή χρήστη από τη λίστα
            DefaultTableModel model = (DefaultTableModel) tblEditUsersProperties.getModel();
            model.removeRow(selectedRow);// Διαγραφή της αντίστοιχης γραμμής από τον πίνακα
        }
    }//GEN-LAST:event_btnDeleteUserPropertyActionPerformed
    // Μέθοδος που ενεργοποιείται όταν ο χρήστης επιλέγει μια γραμμή στον πίνακα
    private void tblEditUsersPropertiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditUsersPropertiesMouseClicked
        int selectedRow = tblEditUsersProperties.getSelectedRow();
        if(selectedRow != -1)
        {
            btnEditUserProperty.setEnabled(true);
            btnDeleteUserProperty.setEnabled(true);
        }
    }//GEN-LAST:event_tblEditUsersPropertiesMouseClicked
    // Μέθοδος που καλείται όταν ενεργοποιείται το παράθυρο
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadUsersPropertiesData();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    // Κύρια μέθοδος εκτέλεσης της φόρμας EditDeleteForm
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        boolean isAdmin = LoggedUserInfo.isLoggedUserAdmin();
        String username = LoggedUserInfo.getLoggedUsername(); 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDeleteForm(username, isAdmin).setVisible(true);
            }
        });
    }
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtInitialPrice;
    private javax.swing.JTextField txtFinalPrice;
    private javax.swing.JLabel lblImagePreview;
    private javax.swing.JButton btnSave;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteUserProperty;
    private javax.swing.JButton btnEditUserProperty;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollPaneEditUsersProperties;
    private javax.swing.JTable tblEditUsersProperties;
    // End of variables declaration//GEN-END:variables
}
