/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package realestateapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import realestateapp.models.User;
/**
 *
 * @author ouran
 */
// Κλάση LoginForm που διαχειρίζεται τη διαδικασία σύνδεσης χρηστών
public class LoginForm extends javax.swing.JFrame {
    
    // Σταθερές για τον προεπιλεγμένο κωδικό πρόσβασης χρηστών και admin
    private static final String DEFAULT_USER_PASSWORD = "pass!23";
    private static final String ADMIN_USERNAME = "admin";
    private static final String ADMIN_PASSWORD = "adm!n123";
    // Μέγιστος αριθμός επιτρεπόμενων αποτυχημένων προσπαθειών σύνδεσης
    private static int MAX_ATTEMPTS = 3;
    private int failedAttempts = 0;
    //// Constructor της φόρμας σύνδεσης
    public LoginForm() {
        initComponents();// Αρχικοποίηση των στοιχείων της φόρμας
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReApp = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReApp.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblReApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReApp.setText("Real Estate App");

        lblUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username:");

        txtUsername.setColumns(15);
        txtUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsername.setToolTipText("Enter your username");

        lblPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password:");

        txtPassword.setColumns(15);
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.setToolTipText("Enter your password");

        btnLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.setToolTipText("Click to login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblReApp))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblReApp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnLogin)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Μέθοδος που καλείται όταν ο χρήστης πατά το κουμπί "LOGIN"
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        boolean isAdmin = false;
        boolean isUserValid = false;
        // Έλεγχος αν είναι ο admin
        if (username.equals(ADMIN_USERNAME) && password.equals(ADMIN_PASSWORD)) 
        {
            isAdmin = true;
            isUserValid = true;
        }
        else
        {
            // Αναζήτηση του χρήστη στη βάση δεδομένων
            for(User user : Database.users)
            {
                if(user.getUsername().equals(username) && password.equals(DEFAULT_USER_PASSWORD))
                {
                    isUserValid = true;
                    break;
                }
            }
        }
        // Αν τα στοιχεία είναι σωστά, προχωράει στη σύνδεση
        if(isUserValid)
        {
            JOptionPane.showMessageDialog(this, "Συνδεθήκατε επιτυχώς!", "Επιτυχία", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            LoggedUserInfo.setLoggedUserInfo(username, username, isAdmin);
            // Αν είναι admin, ανοίγει το AdminPanel
            if(isAdmin)
            {
                AdminPanel adminPanel = new AdminPanel(username);
                adminPanel.setVisible(true);
                adminPanel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
            }
            // Αν είναι χρήστης, ανοίγει το UserPanel 
            else     
            {
                new UserPanel(username).setVisible(true);  // Αν είναι user, ανοίγει το UserPanel
            }
        }
        // Διαχείριση αποτυχημένων προσπαθειών σύνδεσης
        else
        {
            failedAttempts++;
            if(failedAttempts >= MAX_ATTEMPTS)
            {
                JOptionPane.showMessageDialog(this, "Έχετε αποτύχει 3 φορές. Παρακαλώ επικοινωνήστε με τα κεντρικά.",
                    "Σφάλμα", JOptionPane.ERROR_MESSAGE);
                System.exit(0);// Τερματισμός προγράμματος αν ξεπεραστεί ο μέγιστος αριθμός προσπαθειών
            }
            else
            {
                JOptionPane.showMessageDialog(this,
                    "Λάθος στοιχεία! Προσπάθεια " + failedAttempts + " από 3.", 
                    "Προειδοποίηση", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    // Μέθοδος main - Εκκίνηση της εφαρμογής και εμφάνιση της φόρμας σύνδεσης
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblReApp;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
